"""initial

Revision ID: 03b344482ac0
Revises: 
Create Date: 2022-11-19 00:42:51.847448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b344482ac0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('has_pro', sa.Boolean(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('country', sa.VARCHAR(), nullable=True),
    sa.Column('raiting', sa.Float(), nullable=True),
    sa.Column('type', sa.Enum('freelancer', 'client', name='user_type'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_receiver', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('withdraw', 'top_up', 'freezing', name='operation_type'), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_receiver'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_receiver', sa.Integer(), nullable=True),
    sa.Column('id_sender', sa.Integer(), nullable=True),
    sa.Column('mark', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_receiver'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_sender'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_responds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_order', sa.Integer(), nullable=True),
    sa.Column('id_sender', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('message', sa.VARCHAR(), nullable=True),
    sa.Column('deadline_in_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_order'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_sender'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_freelancer', sa.Integer(), nullable=True),
    sa.Column('id_client', sa.Integer(), nullable=True),
    sa.Column('begin_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('deadline_in_days', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('maths', 'programming', name='order_type'), nullable=True),
    sa.Column('status', sa.Enum('opened', 'in_progress', 'under_warranty', 'closed', 'closed_with_compensation', name='order_status'), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_freelancer'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_specialization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('specialization', sa.Enum('maths', 'programming', name='specialization'), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_order', sa.Integer(), nullable=True),
    sa.Column('id_sender', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_order'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['id_sender'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_chats')
    op.drop_table('user_specialization')
    op.drop_table('orders')
    op.drop_table('order_responds')
    op.drop_table('comments')
    op.drop_table('checks')
    op.drop_table('users')
    # ### end Alembic commands ###
