"""change order_responds

Revision ID: d2117e3c5c24
Revises: 03b344482ac0
Create Date: 2022-11-19 17:18:01.722167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2117e3c5c24'
down_revision = '03b344482ac0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_responds_id_order_fkey', 'order_responds', type_='foreignkey')
    op.create_foreign_key(None, 'order_responds', 'orders', ['id_order'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_responds', type_='foreignkey')
    op.create_foreign_key('order_responds_id_order_fkey', 'order_responds', 'users', ['id_order'], ['id'])
    # ### end Alembic commands ###
